version: '3'
services:
  djangoapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 8000
    volumes:
      - ./:/usr/src/app/
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 8000:80
    depends_on:
      - djangoapp

volumes:
  static_volume:
